#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = 'main' ] || [ "$branch" = 'develop' ];
then echo "Commit not allowed in the develop and main branches";
exit 1;
fi
npx lint-staged